branch-defaults:
  development:
    environment: services-dev
  master:
    environment: services-live
environment-defaults:
  services-dev:
    branch: null
    repository: null
global:
  application_name: Services
  default_ec2_keyname: tattle-ec2-key
  default_platform: arn:aws:elasticbeanstalk:ap-south-1::platform/Multi-container
    Docker running on 64bit Amazon Linux/2.19.0
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
