name: dev-deploy

on:
  issue_comment: 
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        COMMENT_BODY: ${{ github.event.comment.body }}
        ISSUE_URL: ${{ github.event.comment.issue_url }}
        USER_LOGIN: ${{ github.event.comment.user.login }}
      run: |
        echo "$COMMENT_BODY"
        echo "$ISSUE_URL"
        echo "$USER_LOGIN"
