name: test

on: 
    issue_comment:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            SHA8: ${GITHUB_SHA::8}

        steps:
            - uses: actions/checkout@v1
            - run: |
                echo "test"
                echo ${issue}
                echo ${comment}