name: test

on: 
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: debug
      run: |
        echo 'test'
        echo ${issue}
        echo ${action}